# Generated by Django 4.2.4 on 2023-08-17 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fruitipedia_project.fruit_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fruitipedia_project.fruit_app.validators.name_should_contain_only_letters_func])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profilemodel')),
            ],
        ),
    ]
