# Generated by Django 4.2.2 on 2023-07-01 09:45

import django.core.validators
from django.db import migrations, models
import my_plant_project.profile_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_project.profile_app.validators.name_must_start_with_a_capital_letter_func])),
                ('last_name', models.CharField(max_length=20, validators=[my_plant_project.profile_app.validators.name_must_start_with_a_capital_letter_func])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
